#!/usr/bin/env bash

if [ -z $(hyprctl clients | grep "class: otter-launcher") ]; 
then hyprctl dispatch exec "foot --app-id otter-launcher -T otter-launcher -e sh -c 'sleep 0.05 && otter-launcher'"; 
else echo application_already_Running; 
    if [ -z $(hyprctl activewindow | grep "class: otter-launcher") ];
	then hyprctl dispatch 'focuswindow class:otter-launcher'
	else hyprctl dispatch killactive none;
    fi
fi
