#!/usr/bin/env bash

export PATH=$HOME/.nix-profile/bin:/run/current-system/sw/bin:$PATH

DEVICE=$(brightnessctl -l | awk -F '"' '/Device/ {print $2; exit}')

if [[ -z "$DEVICE" ]]; then
    echo "Ошибка: устройство подсветки не найдено"
    exit 1
fi

case "$1" in
  up)
    STEP="${2:-5}"
    brightnessctl -d "$DEVICE" set "${STEP}%+"
    ;;
  down)
    STEP="${2:-5}"
    brightnessctl -d "$DEVICE" set "${STEP}%-"
    ;;
  set)
    if [[ -z "$2" ]]; then
      echo "Укажи значение: brightness set 50"
      exit 1
    fi
    brightnessctl -d "$DEVICE" set "$2%"
    ;;
  get)
    current=$(brightnessctl -d "$DEVICE" g)
    max=$(brightnessctl -d "$DEVICE" m)

    current=$(echo "$current" | tr -dc '0-9')
    max=$(echo "$max" | tr -dc '0-9')

    percent=$(( 100 * current / max ))
    echo "$percent"
    ;;
  max)
    brightnessctl -d "$DEVICE" m
    ;;
  *)
    echo "Использование:"
    echo "  brightness up [STEP]    # по умолчанию +5%"
    echo "  brightness down [STEP]  # по умолчанию -5%"
    echo "  brightness set <NN>     # установить NN %"
    echo "  brightness get          # вывести текущую яркость в %"
    echo "  brightness max          # вывести максимальное значение"
    exit 1
    ;;
esac

