# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cdce22bb-e870-4d87-9205-2323b7a0b451";
    fsType = "btrfs";
    options = ["subvol=@" "compress=zstd" "noatime" "ssd" "space_cache=v2" "discard=async"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1B33-3B87";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/19873623-2771-4542-a093-d315ae6fc506";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/75f4cf45-03f7-4c97-84ed-1ae500a3190e";
    fsType = "btrfs";
    options = ["subvol=@home" "noatime" "compress=zstd" "space_cache=v2" "ssd" "discard=async"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/8f8fd145-8867-4f84-9754-d6b9230a1c7a";
    fsType = "btrfs";
    options = ["noatime" "compress=zstd" "space_cache=v2" "ssd" "discard=async"];
  };

  fileSystems."/tmp" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = ["mode=1777" "size=7G"];
  };

  swapDevices = [
    {
      device = "/data/swapfile";
      size = 32 * 1024;
      priority = 50;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
